[theme]
primaryColor="#007bff"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f8f9fa"
textColor="#333333"
font="sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false